---
image:
  pullPolicy: Always

MASTER_NODES_LABEL: "node-role.kubernetes.io/control-plane"

networking:
  ENABLE_SSL: true

func:
  ENABLE_NP: false

ipv4:
  POD_CIDR: "10.55.0.0/18"
  POD_GATEWAY: "10.55.0.1"
  SVC_CIDR: "10.55.64.0/20"
  JOIN_CIDR: "100.64.0.0/16"

cni_conf:
  CNI_CONFIG_PRIORITY: "10"
  MOUNT_LOCAL_BIN_DIR: false

OPENVSWITCH_DIR: "/var/lib/openvswitch"
OVN_DIR: "/var/lib/ovn"
DISABLE_MODULES_MANAGEMENT: true
