---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - provider-network.yaml
configMapGenerator:
  - name: kubeovn-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - name-reference.yaml
