---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux Kustomizations
  - flux-system
  - kube-ovn/app.yaml
  - cilium/app.yaml
  - kubelet-csr-approver/app.yaml
  - cert-manager/app.yaml
  - piraeus-operator/app.yaml
  - linstor/app.yaml
  - kubevirt
