---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux Kustomizations
  - flux-system
  - cilium/app.yaml
  - kube-ovn/app.yaml
  # - kube-ovn/configs.yaml
  - kubelet-csr-approver/app.yaml
  - cert-manager/app.yaml
  - piraeus-datastore
  # - linstor/app.yaml
  # - kubevirt/app.yaml
  # - kubevirt/addons.yaml
