---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/app.yaml
  - kubelet-csr-approver/app.yaml
  - flux-system
  - metrics-server/kustomize.yaml
  - cert-manager/app.yaml
  - piraeus-datastore
  - kubevirt/app.yaml
  - kubevirt/addons.yaml
