---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  #nodeSelector:
  #  node-role.kubernetes.io/linstor: ""
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  # apiTLS:
  #   certManager:
  #     name: linstor-api-ca
  #     kind: Issuer
