---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan45
spec:
  id: 45
  provider: bridge1
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: cluster-network
spec:
  protocol: IPv4
  cidrBlock: 192.168.45.0/24
  gateway: 192.168.45.1
  vlan: vlan45
  namespaces:
    - cluster-network
