---
creation_rules:
  - # IMPORTANT: Keep this rule first
    path_regex: talos/.+\.sops\.ya?ml
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    key_groups:
      - age:
          - age13g8vu0uypup5ulq059xrs0gh4nkecvhhpkqmjdp3gpuc4w8q9c4sjys65q
