---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  talos: .taskfiles/talos/taskfile.yaml
  flux: .taskfiles/flux/taskfile.yaml
  k8s: .taskfiles/k8s/taskfile.yaml

tasks:
  default:
    silent: true
    cmd: go-task -l
