---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.2.0/kubevirt-operator.yaml
patches:
  # add podsecurity admission settings to namespace
  - target:
      group: v1
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
      value: { "pod-security.kubernetes.io/enforce": "privileged" }
