---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: piraeus-operator
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: piraeus-operator
      version: v1.14.5
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: piraeus-datastore
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    tls:
      certManagerIssuerRef:
        name: ca-bootstrapper
        kind: Issuer
