# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: piraeus-charts
# spec:
#   interval: 24h
#   url: https://piraeus.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piraeus-operator-chart
spec:
  interval: 24h
  url: https://github.com/piraeusdatastore/piraeus-operator
  ref:
    branch: v2
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
