---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: piraeus-datastore-internal-ca
spec:
  isCA: true
  commonName: piraeus-datastore-internal-ca
  secretName: piraeus-datastore-internal-ca
  duration: 87600h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: piraeus-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: piraeus-datastore-internal-ca
spec:
  ca:
    secretName: piraeus-datastore-internal-ca
