---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linstor-internal-ca
spec:
  ca:
    secretName: linstor-internal-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linstor-api-ca
spec:
  ca:
    secretName: linstor-api-ca
