---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: piraeus-datastore
spec:
  apiTLS:
    certManager:
      name: linstor-api-ca
      kind: Issuer
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
