---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: node01-storagepool
spec:
  nodeSelector:
    topology.kubernetes.io/region: host-cluster
    topology.kubernetes.io/zone: node1
  storagePools:
    - name: pool1
      zfsThinPool:
        zPool: zpool-local/piraeus-datastore
