---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: node01-storagepool
spec:
  nodeSelector:
    topology.kubernetes.io/region: fleet
    topology.kubernetes.io/zone: node01
  storagePools:
    - name: pool1
      zfsThinPool:
        zPool: storage
      source:
        hostDevices:
          - /dev/sdc
          - /dev/sdd
          - /dev/sde
          - /dev/sdf
