---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: node01-storagepool
spec:
  nodeSelector:
    topology.kubernetes.io/region: fleet
    topology.kubernetes.io/zone: node01
  storagePools:
    - name: pool1
      zfsThinPool:
        zPool: storage
      source:
        hostDevices:
          - /dev/disk/by-id/scsi-35000c500970f93c3
          - /dev/disk/by-id/scsi-35000c5009710144b
          - /dev/disk/by-id/scsi-35000c50097102613
          - /dev/disk/by-id/scsi-35000c50097120007
