---
# -- cluster mesh configuration.
cluster:
  name: host-cluster
  id: 100

# -- roll out cilium agent pods automatically when configmap is updated.
rollOutCiliumPods: true

# -- use Talos KubePrism endpoint for k8s service host
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

# -- Enable native routing mode
routingMode: native
ipv4NativeRoutingCIDR: 192.168.55.0/24

# -- disable BPF and IPv4 masquerading.
bpf:
  masquerade: false

# -- disable masquerading of IPv4 traffic.
enableIPv4Masquerade: false

# -- configure CNI for chaning for kubeovn.
cni:
  chainingMode: generic-veth
  customConf: true
  configMap: cni-configuration

# -- configure IPAM from kubernetes configuration.
ipam:
  mode: kubernetes

# -- configure the kube-proxy replacement in Cilium BPF datapath.
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

# -- configure the maglev table size and hashseed.
maglev:
  tableSize: 1021
  hashSeed: "kjS9P8J5eNMVcY2x"

# -- configure loadBalancer balancing algorithm.
loadBalancer:
  algorithm: maglev

# -- configure the cilium-operator component.
operator:
  rollOutPods: true
  replicas: 1

# -- disable Hubble temporarily, default enabled.
hubble:
  enabled: false

# -- enable external IP service support.
externalIPs:
  enabled: true

# -- configure cgroup related configuration for talos systems.
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# -- configure security context that is compatible with talos.
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
