---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - cni-configmap.yaml
  - release.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - cilium-values.yaml
configurations:
  - name-reference.yaml
