---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Base Kustomizations
  - namespace.yaml
  # Tenant Kustomizations
  - milton-home.yaml
  - milton-cluster.yaml
