---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 2h
  path: ./kubernetes/tenants
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  timeout: 3m
  wait: false
