---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  cleanup:failed:
    desc: Clean-up pods with 'Failed' status
    cmds:
      - kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true

  cleanup:succeeded:
    desc: Clean-up pods with 'Succeeded' status
    cmds:
      - kubectl delete pods --field-selector status.phase=Succeeded -A --ignore-not-found=true

  # Maintain a clean execution
  default:
    silent: true
    cmds: [task -l]
