---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: snapshot-controller
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: piraeus-datastore
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    webhook:
      enabled: false
      tls:
        certManagerIssuerRef:
          name: piraeus-selfsigned
          kind: Issuer
