---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kubevirt
  namespace: flux-system
spec:
  targetNamespace: kubevirt
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 2h
  path: ./kubernetes/system/kubevirt/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  wait: false
  dependsOn:
    - name: linstor
